version: "2"
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - gosec
    - gocyclo
    - ineffassign
    - unused
    - misspell
    - gocritic
  settings:
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
formatters:
  enable:
    - gofmt
    - goimports
